### ISSUE TITLE
No columns found?

### ISSUE THREAD

**Issue by synatree** [airmoi/yii2-fmpconnector#1]
I am getting no results from gii when querying my schema.  Any thoughts?

**Comment by airmoi** [comment]
Are your security settings set properly ?
Gii will show you table occurrences, not base table.

I also had issues with gii's autocomplete, what happen if you manually
enter your table occurrence's names ?

2016-03-30 3:41 GMT+02:00 SynaTree notifications@github.com:

**Comment by synatree** [comment]
After digging a bit more:  In Schema::parseSchema, the query "SELECT BaseTableName, TableName FROM FileMaker_Tables WHERE BaseTableName IS NOT NULL" returns an object filled with strange strings:

``` javascript
[
        'BaseTableName' => '' . "\0" . '[c',
        'TableName' => '' . "\0" . '[c',
    ],
    [
        'BaseTableName' => '' . "\0" . '[c' . "\0" . '' . "\0" . '',
        'TableName' => '' . "\0" . '[c' . "\0" . '' . "\0" . '',
    ],
    [
        'BaseTableName' => '' . "\0" . '[c' . "\0" . '' . "\0" . '',
        'TableName' => '' . "\0" . '[c' . "\0" . '' . "\0" . 'H[c' . "\0" . '' . "\0" . 'Y' . "\0" . '' . "\0" . '' . "\0" . '',
    ], ... 
```

Which makes me think this could be encoding related somehow?

**Comment by airmoi** [comment]
Did you configure your ODBC driver to be utf8 encoded (you'll find this
options in the 'advanced language' menu) ?

2016-03-30 21:13 GMT+02:00 SynaTree notifications@github.com:

**Comment by synatree** [comment]
In fact, I had not... when I updated that setting I got the following error from Yii:

```
Invalid Parameter – yii\base\InvalidParamException

Malformed UTF-8 characters, possibly incorrectly encoded.
```

Here is what came out of the database that time:

``` javascript
[
    [
        'BaseTableName' => '' . "\0" . 'λc' . "\0" . '' . "\0" . 'q',
        'TableName' => '' . "\0" . 'ͻc' . "\0" . '' . "\0" . ' ',
    ],
    [
        'BaseTableName' => '' . "\0" . 'λc' . "\0" . '' . "\0" . 'ques',
        'TableName' => '' . "\0" . 'ͻc' . "\0" . '' . "\0" . ' λ',
    ],
    [
        'BaseTableName' => '' . "\0" . 'λc' . "\0" . '' . "\0" . '',
        'TableName' => '' . "\0" . 'ͻc' . "\0" . '' . "\0" . '',
    ],
    [
        'BaseTableName' => '' . "\0" . 'λc',
        'TableName' => '' . "\0" . 'ͻc',
    ],
    [
        'BaseTableName' => '' . "\0" . 'λc' . "\0" . '' . "\0" . '',
        'TableName' => '' . "\0" . 'ͻc' . "\0" . '' . "\0" . '',
    ],
]
```

**Comment by synatree** [comment]
And here is what the query returned in a simple ODBC browser application:

![image](https://cloud.githubusercontent.com/assets/7294077/14186227/56c0fa28-f74b-11e5-8289-ea4f95c1ac4b.png)

I got to thinking that maybe the issue is with 32bit vs 64bit DSNs, because the screenshot above is from an application that uses a 32bit copy of the same DSN that my Yii application uses.  So, I switched the configuration around to use the 32bit DSN from Yii, which resulted in an error: `The specified DSN contains an architecture mismatch between the Driver and Application (IM014)` which makes sense, since PHP is 64bit on my system.  I am still stumped as to why this simple data is getting mangled on it's way from FileMaker to PHP.

https://bugs.php.net/bug.php?id=54169 maybe related?

**Comment by synatree** [comment]
AHA!  I figured it out.  For future reference, make sure you have checked the "Describe text fields as long varchar" to prevent this behavior.

![image](https://cloud.githubusercontent.com/assets/7294077/14186810/1d7feadc-f74e-11e5-8cb2-1352486cfdf7.png)

**Comment by airmoi** [comment]
Missed this one ! Good to know (I always tick this box)
