### ISSUE TITLE
Getting unknown property: app\models\OUTBOX::zlg_creaAccount

### ISSUE THREAD

**Issue by opeah** [airmoi/yii2-fmpconnector#3]
Error when I submit contact form.

PHP 7.1.3

<img width="1680" alt="screenshot 2019-03-07 at 11 49 37" src="https://user-images.githubusercontent.com/31569566/53952814-26d03580-40d2-11e9-9462-df0a05aaa9a5.png">

**Comment by airmoi** [comment]
Project issue not related to this library
